version: "2"
linters:
  enable:
    - err113
    - errname
    - errorlint
    - makezero
    - nilerr
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - thelper
    - unconvert
    - unparam
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
