linters:
    enable:
        - errname
        - errorlint
        - err113
        - makezero
        - nilerr
        - paralleltest
        - prealloc
        - predeclared
        - revive
        - thelper
        - unconvert
        - unparam
        - wastedassign
