run:
  timeout: 10m

  # Run linters over integration tests
  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - stylecheck
    - gosec
    - goimports
