# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/1.5.0/tools/projmgr/schemas/cdefault.schema.json

default:
  compiler: AC6

  misc:
    - compiler: AC6
      C*:
        - -Wno-macro-redefined
        - -Wno-pragma-pack
        - -Wno-parentheses-equality
      C:
        - -std=c99
      Link:
        - --entry=Reset_Handler
        - --diag_suppress 6314,6848
