/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'EventStatistic.Debug+AVH' 
 * Target:  'Debug+AVH' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"

/* ARM::CMSIS-View:Event Recorder&Semihosting@1.6.0 */
#define RTE_CMSIS_View_EventRecorder
#define RTE_CMSIS_View_EventRecorder_DAP
#define RTE_CMSIS_View_EventRecorder_Semihosting
/* ARM::Device:Native Driver:SysCounter@1.1.0 */
#define RTE_SYSCOUNTER      1
/* ARM::Device:Native Driver:Timeout@1.0.0 */
#define RTE_TIMEOUT      1


#endif /* RTE_COMPONENTS_H */
