/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'Fault_S.Debug+B-U585I-IOT02A' 
 * Target:  'Debug+B-U585I-IOT02A' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDERR:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Breakpoint     /* CMSIS-Compiler STDERR: Breakpoint */
/* ARM::CMSIS-Compiler:STDIN:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Breakpoint      /* CMSIS-Compiler STDIN: Breakpoint */
/* ARM::CMSIS-Compiler:STDOUT:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Breakpoint     /* CMSIS-Compiler STDOUT: Breakpoint */
/* ARM::CMSIS-View:Fault:Storage@1.1.0 */
#define RTE_CMSIS_View_Fault_Storage
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32u5xx.h"


#endif /* RTE_COMPONENTS_H */
