name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '.github/markdown-link-check.jsonc'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  markdown-lint:
    name: Lint markdown files
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout devtools
        uses: actions/checkout@v4

      - name: Register markdownlint warning matcher
        run: |
          echo "::add-matcher::.github/markdownlint.json"

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          config: '.github/markdownlint.jsonc'

      - name: Remove markdownlint warning matcher
        if: always()
        run: |
          echo "::remove-matcher owner=markdownlint::"

      - uses: gaurav-nelson/github-action-markdown-link-check@master
        if: always()
        with:
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          base-branch: ${{ github.base_ref }}
          config-file: '.github/markdown-link-check.jsonc'
