name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '.github/lychee.toml'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  markdown-checkt:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/markdown-lint.yml@v3.0.1
    with:
      lint-config: '.github/markdownlint.jsonc'
      link-check-config: '.github/lychee.toml'
